<a href="https://colab.research.google.com/github/ncrowder/maven/blob/main/maven_drill_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [107]:
import pandas as pd

In [108]:
df = pd.read_csv('https://maven-datasets.s3.us-east-1.amazonaws.com/Data+Drills/OfficeSpace.csv')

In [109]:
df.head()

      Employee Name      Manager Name
0     Bill Lumbergh               NaN
1       Bob Slydell     Bill Lumbergh
2        Bob Porter     Bill Lumbergh
3  Linda M. Grayson     Bill Lumbergh
4      Dom Portwood  Linda M. Grayson

In [110]:
df.columns = ['employee','manager']

In [111]:
df.head()

           employee           manager
0     Bill Lumbergh               NaN
1       Bob Slydell     Bill Lumbergh
2        Bob Porter     Bill Lumbergh
3  Linda M. Grayson     Bill Lumbergh
4      Dom Portwood  Linda M. Grayson

In [112]:
def managers(row):
  bosses = [row['employee']]
  manager = row['manager']
  while pd.notna(manager):
    bosses.append(manager)
    manager = df[df.employee == manager]['manager'].iloc[0]
  return " > ".join(bosses[::-1])

In [113]:
df['Heirarchy'] = df.apply(managers,axis=1)

In [114]:
df

,employee,manager,Heirarchy
0,Bill Lumbergh,NaN,Bill Lumbergh
1,Bob Slydell,Bill Lumbergh,Bill Lumbergh > Bob Slydell
2,Bob Porter,Bill Lumbergh,Bill Lumbergh > Bob Porter
3,Linda M. Grayson,Bill Lumbergh,Bill Lumbergh > Linda M. Grayson
4,Dom Portwood,Linda M. Grayson,Bill Lumbergh > Linda M. Grayson > Dom Portwood
5,Wendy L. Hargrove,Linda M. Grayson,Bill Lumbergh > Linda M. Grayson > Wendy L. Ha...
6,Tom Smykowski,Linda M. Grayson,Bill Lumbergh > Linda M. Grayson > Tom Smykowski
7,Nathan R. Ross,Linda M. Grayson,Bill Lumbergh > Linda M. Grayson > Nathan R. Ross
8,Peter Gibbons,Dom Portwood,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...
9,Cheryl T. Ackerman,Peter Gibbons,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...
10,Samir Nagheenanajar,Dom Portwood,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...
11,Michael Bolton,Samir Nagheenanajar,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...
12,Nathan C. Carter,Dom Portwood,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...
13,Lydia Bennett,Nathan C. Carter,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...
14,Greg S. Torres,Nathan C. Carter,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...
15,Alice L. Munroe,Nathan C. Carter,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...
16,Peggy Carlson,Wendy L. Hargrove,Bill Lumbergh > Linda M. Grayson > Wendy L. Ha...
17,Anne Martinez,Wendy L. Hargrove,Bill Lumbergh > Linda M. Grayson > Wendy L. Ha...
18,Fred Wilkinson,Wendy L. Hargrove,Bill Lumbergh > Linda M. Grayson > Wendy L. Ha...
19,Derek P. Phillips,Tom Smykowski,Bill Lumbergh > Linda M. Grayson > Tom Smykows...
20,Sarah J. Greene,Derek P. Phillips,Bill Lumbergh > Linda M. Grayson > Tom Smykows...
21,Alan B. Peterson,Nathan R. Ross,Bill Lumbergh > Linda M. Grayson > Nathan R. R...
22,Maria D. Sanchez,Alan B. Peterson,Bill Lumbergh > Linda M. Grayson > Nathan R. R...
23,Bobbie K. Jenkins,Alan B. Peterson,Bill Lumbergh > Linda M. Grayson > Nathan R. R...
24,Milton Waddams,Tom Smykowski,Bill Lumbergh > Linda M. Grayson > Tom Smykows...

In [75]:
# df['Direct Reports'] = df.groupby('manager')['employee'].transform("count")

In [115]:
direct = df.groupby('manager')['employee'].count().rename_axis('employee').rename('Direct Reports').reset_index()
direct

               employee  Direct Reports
0      Alan B. Peterson               2
1         Bill Lumbergh               3
2     Derek P. Phillips               1
3          Dom Portwood               3
4      Linda M. Grayson               4
5      Nathan C. Carter               3
6        Nathan R. Ross               1
7         Peter Gibbons               1
8   Samir Nagheenanajar               1
9         Tom Smykowski               2
10    Wendy L. Hargrove               3

In [116]:
df1 = df.merge(direct, on = 'employee', how = 'left')
df1.fillna(0,inplace = True)
df1

,employee,manager,Heirarchy,Direct Reports
0,Bill Lumbergh,0,Bill Lumbergh,3.0
1,Bob Slydell,Bill Lumbergh,Bill Lumbergh > Bob Slydell,0.0
2,Bob Porter,Bill Lumbergh,Bill Lumbergh > Bob Porter,0.0
3,Linda M. Grayson,Bill Lumbergh,Bill Lumbergh > Linda M. Grayson,4.0
4,Dom Portwood,Linda M. Grayson,Bill Lumbergh > Linda M. Grayson > Dom Portwood,3.0
5,Wendy L. Hargrove,Linda M. Grayson,Bill Lumbergh > Linda M. Grayson > Wendy L. Ha...,3.0
6,Tom Smykowski,Linda M. Grayson,Bill Lumbergh > Linda M. Grayson > Tom Smykowski,2.0
7,Nathan R. Ross,Linda M. Grayson,Bill Lumbergh > Linda M. Grayson > Nathan R. Ross,1.0
8,Peter Gibbons,Dom Portwood,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...,1.0
9,Cheryl T. Ackerman,Peter Gibbons,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...,0.0
10,Samir Nagheenanajar,Dom Portwood,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...,1.0
11,Michael Bolton,Samir Nagheenanajar,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...,0.0
12,Nathan C. Carter,Dom Portwood,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...,3.0
13,Lydia Bennett,Nathan C. Carter,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...,0.0
14,Greg S. Torres,Nathan C. Carter,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...,0.0
15,Alice L. Munroe,Nathan C. Carter,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...,0.0
16,Peggy Carlson,Wendy L. Hargrove,Bill Lumbergh > Linda M. Grayson > Wendy L. Ha...,0.0
17,Anne Martinez,Wendy L. Hargrove,Bill Lumbergh > Linda M. Grayson > Wendy L. Ha...,0.0
18,Fred Wilkinson,Wendy L. Hargrove,Bill Lumbergh > Linda M. Grayson > Wendy L. Ha...,0.0
19,Derek P. Phillips,Tom Smykowski,Bill Lumbergh > Linda M. Grayson > Tom Smykows...,1.0
20,Sarah J. Greene,Derek P. Phillips,Bill Lumbergh > Linda M. Grayson > Tom Smykows...,0.0
21,Alan B. Peterson,Nathan R. Ross,Bill Lumbergh > Linda M. Grayson > Nathan R. R...,2.0
22,Maria D. Sanchez,Alan B. Peterson,Bill Lumbergh > Linda M. Grayson > Nathan R. R...,0.0
23,Bobbie K. Jenkins,Alan B. Peterson,Bill Lumbergh > Linda M. Grayson > Nathan R. R...,0.0
24,Milton Waddams,Tom Smykowski,Bill Lumbergh > Linda M. Grayson > Tom Smykows...,0.0

In [117]:
dfexpanded = df.assign(heirarchy = df.Heirarchy.str.split(' > ')).explode('heirarchy')

In [118]:
dfexpanded

,employee,manager,Heirarchy,heirarchy
0,Bill Lumbergh,NaN,Bill Lumbergh,Bill Lumbergh
1,Bob Slydell,Bill Lumbergh,Bill Lumbergh > Bob Slydell,Bill Lumbergh
1,Bob Slydell,Bill Lumbergh,Bill Lumbergh > Bob Slydell,Bob Slydell
2,Bob Porter,Bill Lumbergh,Bill Lumbergh > Bob Porter,Bill Lumbergh
2,Bob Porter,Bill Lumbergh,Bill Lumbergh > Bob Porter,Bob Porter
...,...,...,...,...
23,Bobbie K. Jenkins,Alan B. Peterson,Bill Lumbergh > Linda M. Grayson > Nathan R. R...,Bobbie K. Jenkins
24,Milton Waddams,Tom Smykowski,Bill Lumbergh > Linda M. Grayson > Tom Smykows...,Bill Lumbergh
24,Milton Waddams,Tom Smykowski,Bill Lumbergh > Linda M. Grayson > Tom Smykows...,Linda M. Grayson
24,Milton Waddams,Tom Smykowski,Bill Lumbergh > Linda M. Grayson > Tom Smykows...,Tom Smykowski
24,Milton Waddams,Tom Smykowski,Bill Lumbergh > Linda M. Grayson > Tom Smykows...,Milton Waddams

In [119]:
total = dfexpanded.groupby('heirarchy').employee.agg(lambda x: x.count() -1).reset_index()
total = total.rename(columns = {'heirarchy':'employee','employee': 'Total Reports'})
total

               employee  Total Reports
0      Alan B. Peterson              2
1       Alice L. Munroe              0
2         Anne Martinez              0
3         Bill Lumbergh             24
4            Bob Porter              0
5           Bob Slydell              0
6     Bobbie K. Jenkins              0
7    Cheryl T. Ackerman              0
8     Derek P. Phillips              1
9          Dom Portwood              8
10       Fred Wilkinson              0
11       Greg S. Torres              0
12     Linda M. Grayson             21
13        Lydia Bennett              0
14     Maria D. Sanchez              0
15       Michael Bolton              0
16       Milton Waddams              0
17     Nathan C. Carter              3
18       Nathan R. Ross              3
19        Peggy Carlson              0
20        Peter Gibbons              1
21  Samir Nagheenanajar              1
22      Sarah J. Greene              0
23        Tom Smykowski              3
24    Wendy L. Hargrove              3

In [120]:
df2 = df1.merge(total, on = 'employee', how = 'left')
df2

,employee,manager,Heirarchy,Direct Reports,Total Reports
0,Bill Lumbergh,0,Bill Lumbergh,3.0,24
1,Bob Slydell,Bill Lumbergh,Bill Lumbergh > Bob Slydell,0.0,0
2,Bob Porter,Bill Lumbergh,Bill Lumbergh > Bob Porter,0.0,0
3,Linda M. Grayson,Bill Lumbergh,Bill Lumbergh > Linda M. Grayson,4.0,21
4,Dom Portwood,Linda M. Grayson,Bill Lumbergh > Linda M. Grayson > Dom Portwood,3.0,8
5,Wendy L. Hargrove,Linda M. Grayson,Bill Lumbergh > Linda M. Grayson > Wendy L. Ha...,3.0,3
6,Tom Smykowski,Linda M. Grayson,Bill Lumbergh > Linda M. Grayson > Tom Smykowski,2.0,3
7,Nathan R. Ross,Linda M. Grayson,Bill Lumbergh > Linda M. Grayson > Nathan R. Ross,1.0,3
8,Peter Gibbons,Dom Portwood,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...,1.0,1
9,Cheryl T. Ackerman,Peter Gibbons,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...,0.0,0
10,Samir Nagheenanajar,Dom Portwood,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...,1.0,1
11,Michael Bolton,Samir Nagheenanajar,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...,0.0,0
12,Nathan C. Carter,Dom Portwood,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...,3.0,3
13,Lydia Bennett,Nathan C. Carter,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...,0.0,0
14,Greg S. Torres,Nathan C. Carter,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...,0.0,0
15,Alice L. Munroe,Nathan C. Carter,Bill Lumbergh > Linda M. Grayson > Dom Portwoo...,0.0,0
16,Peggy Carlson,Wendy L. Hargrove,Bill Lumbergh > Linda M. Grayson > Wendy L. Ha...,0.0,0
17,Anne Martinez,Wendy L. Hargrove,Bill Lumbergh > Linda M. Grayson > Wendy L. Ha...,0.0,0
18,Fred Wilkinson,Wendy L. Hargrove,Bill Lumbergh > Linda M. Grayson > Wendy L. Ha...,0.0,0
19,Derek P. Phillips,Tom Smykowski,Bill Lumbergh > Linda M. Grayson > Tom Smykows...,1.0,1
20,Sarah J. Greene,Derek P. Phillips,Bill Lumbergh > Linda M. Grayson > Tom Smykows...,0.0,0
21,Alan B. Peterson,Nathan R. Ross,Bill Lumbergh > Linda M. Grayson > Nathan R. R...,2.0,2
22,Maria D. Sanchez,Alan B. Peterson,Bill Lumbergh > Linda M. Grayson > Nathan R. R...,0.0,0
23,Bobbie K. Jenkins,Alan B. Peterson,Bill Lumbergh > Linda M. Grayson > Nathan R. R...,0.0,0
24,Milton Waddams,Tom Smykowski,Bill Lumbergh > Linda M. Grayson > Tom Smykows...,0.0,0

In [121]:
df2['Total Reports'].sum()

np.int64(70)